spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s

  application:
    name: api-gateway
    version: 1.0.0
  banner:
    location: classpath:banner.txt
  config:
    import: optional:file:./profile.properties

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
    instances:
      user-service:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
