EurekaOrigin : http://localhost:8761

spring:
  application:
    name:  venue-service
  config:
    import: optional:file:./profile.properties

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5435}/${DB_NAME:venue_db}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 0
