EurekaOrigin : http://discovery-server:8761

kafka:
  host: kafka
  port: 9092

loki:
  host: loki
  port: 3100

tempo:
  host: tempo
  zipkin-port: 9411
#  otlp-port: 4318

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.loadbalancer: INFO
