-- V1: initial schema for analytics-service (analytics_db)

CREATE TABLE sales_records (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    event_id          varchar(36)  NOT NULL,
    organization_name varchar(150),
    sale_date         date         NOT NULL,
    tickets_sold      integer,
    revenue           numeric(14, 2),
    CONSTRAINT pk_sales_records PRIMARY KEY (id),
    CONSTRAINT uq_sales_event_date UNIQUE (event_id, sale_date)
);

CREATE TABLE event_analytics (
    event_id              varchar(36) NOT NULL,
    organization_name     varchar(150),
    created_by            varchar(36),
    title                 varchar(255),
    status                varchar(20) NOT NULL,
    total_revenue         numeric(14, 2),
    total_tickets_sold    integer,
    capacity              integer,
    total_failed_payments integer,
    start_date_time       timestamp with time zone,
    end_date_time         timestamp with time zone,
    last_event_timestamp  timestamp with time zone,
    CONSTRAINT pk_event_analytics PRIMARY KEY (event_id)
);

CREATE TABLE processed_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    topic        varchar(80) NOT NULL,
    message_id   varchar(36) NOT NULL,
    processed_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_processed_events PRIMARY KEY (id),
    CONSTRAINT uq_processed_topic_msg UNIQUE (topic, message_id)
);
